version: '3.8'
services:
  front:
    build: .
    volumes:
    - ./front:/opt/app
    links:
    - back
    ports:
    - 80:80
  back:
    image: nginx:alpine
    volumes:
    - ./back:/usr/share/nginx/html
